# platform :ios, '10.0'

target 'nasaApp' do
  use_frameworks!

  pod 'SwifterSwift', '~> 3.2.0'
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'RxFlow', '~> 2.0.0'
  pod 'Moya/RxSwift', '~> 12.0.1'
  pod 'RxDataSources', '~> 3.1.0'
	pod 'Kingfisher', '~> 4.0'
	pod 'RxGesture', '~> 2.1.0'
end
