target 'nasaApp' do
  use_frameworks!

  pod 'SwifterSwift'
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'RxFlow'
  pod 'Moya/RxSwift', '~> 12.0.1'
  pod 'RxDataSources', '~> 3.1.0'
	pod 'Kingfisher', '~> 4.0'
	pod 'RxGesture'

	target 'nasaAppTests' do
		use_frameworks!

		pod 'RxTest'
	end
end


